### ISSUE TITLE
과제관련

### ISSUE THREAD

**Issue by z1ggy-o** [CAU-DOSC/TransSum07#1]
여러분 연락처를 몰라서 여기서 얘기할게요.
우리 이번에 page수로 나눠서 할까요? 아니면 어떻게 하는지 모르는데
혹시 아직 시작한 친구가 없으면 제가 면저 앞 세 page를 해 볼게요.

**Comment by Rapha0814** [comment]
https://open.kakao.com/o/gQoKNKK
연락의 편의를 위해서 카카오톡 오픈 채팅방을 만들었습니다.
들어오셔서 과제 관련해서 의견 있으시면 말씀해주세요
저는 저희가 하는게 18 page니까 3page씩 2명이 하고 4page씩 3명이 하면 좋을것 같은데 다른 분들은 어떻게 생각하시나요?
